/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package allswellhospital.View;

import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import models.ConsultantDoctor;
import models.DBManager;
import models.Drug;
import models.Patient;
import models.PatientsDrugs;

/**
 *
 * @author Harris
 */
public class ConsultantTreatPatient extends javax.swing.JFrame {

    /**
     * Creates new form ConsultantTreatPatient
     */
    private ConsultantDoctor loggedInConsultant;
    private Patient selectedPatient;
    
    private HashMap<Integer,Drug>drugs;
    private Drug selectedDrug;
    
    private HashMap<Integer,PatientsDrugs>patientsDrugs;
    private PatientsDrugs selectedPatientsDrug;
    
    DefaultListModel model2 = new DefaultListModel();
    
    public ConsultantTreatPatient(ConsultantDoctor consultantIn, Patient patientIn) {
        loggedInConsultant = consultantIn;
        selectedPatient = patientIn;
        
        DBManager db = new DBManager();
        drugs = db.loadDrugs();
        patientsDrugs = db.loadPatientsDrugs();
        
        initComponents();
        //sets the text lable with patients name and number
        lblPatient.setText(selectedPatient.toString());
        
        //This part of the code fills the Listbox with drugs to select
        DefaultListModel model = new DefaultListModel();

         for(Map.Entry<Integer,Drug> drugEntry : drugs.entrySet())
        {
            Drug actualDrug = drugEntry.getValue();
                model.addElement(actualDrug);
        }
        lstDrugs.setModel(model);
        
        
        //This part of the code fills the Listbox with patients drugs
        

         for(Map.Entry<Integer,PatientsDrugs> patientsDrugEntry : patientsDrugs.entrySet())
        {
            int tempPatientId = patientsDrugEntry.getValue().getPatientId();
            int patientId = selectedPatient.getPatientNo();
            PatientsDrugs actualPatientsDrug = patientsDrugEntry.getValue();
            if(patientId == tempPatientId)
            {
                
                model2.addElement(actualPatientsDrug);
            }
            
        }
        lstPatientsDrugs.setModel(model2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPatient = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDrugs = new javax.swing.JList<>();
        lblMessage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPatientsDrugs = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnDeletePatientsDrug = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Prescribe Drugs To Patient");

        lblPatient.setText("PatientName");

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lstDrugs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDrugsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDrugs);

        lstPatientsDrugs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPatientsDrugsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPatientsDrugs);

        btnAdd.setText("Add To Patients Drugs");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDeletePatientsDrug.setText("Delete Patients Drug");
        btnDeletePatientsDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePatientsDrugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatient)
                            .addComponent(jLabel1))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletePatientsDrug))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnReturn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPatient)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDeletePatientsDrug))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        ConsultantViewPatientTeam team = new ConsultantViewPatientTeam(loggedInConsultant);
        this.dispose();
        team.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void lstDrugsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDrugsValueChanged
        //this sets the drugs which is selected in the drug list box
        Object selectedDrugObject = (Object)lstDrugs.getSelectedValue();
        
        selectedDrug = (Drug)selectedDrugObject;
        
        lblMessage.setText("");
    }//GEN-LAST:event_lstDrugsValueChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // this checks to see if a ward has been selected
        if(lstDrugs.getSelectedIndex() != -1)
        {     
            int drugId = selectedDrug.getDrugId();
            int patientId = selectedPatient.getPatientNo();
            String drugName = selectedDrug.getDrugName();
            String dosage = selectedDrug.getDosage();
            double price = selectedDrug.getPrice();
            
             
            
                //the patients details are set
                PatientsDrugs newPatientsDrug = new PatientsDrugs( patientId, drugId, drugName, dosage, price );
                DBManager db = new DBManager();
                //DB managers method is called (admit patient)
                db.addPatientsDrug(newPatientsDrug);
                lblMessage.setText("New Patients Drug Added Successfully");
                
                //This part of the code fills the Listbox with patients Drugs to select
        //This part of the code fills the Listbox with patients drugs
        
         model2.addElement(newPatientsDrug);

         
        lstPatientsDrugs.setModel(model2);
             
            
        }
        else
        {
            lblMessage.setText("Please select a Drug to add!");
        }
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeletePatientsDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePatientsDrugActionPerformed
        //it enures a drug is selected
        if(lstPatientsDrugs.getSelectedIndex() != -1)
        {
            //it selects drug then calls a funtion in DBManager to delete the drug
            String drugName = selectedPatientsDrug.toString();
            DBManager db = new DBManager();
            db.deletePatientsDrug(selectedPatientsDrug);
            patientsDrugs.remove(selectedPatientsDrug.getDrugLineId());
            
            
            //This part of the code fills the Listbox with drugs to select
        

            model2.removeElement(selectedPatientsDrug);
         
        lstPatientsDrugs.setModel(model2);
                    //confirmation that the Drug is deleted
            lblMessage.setText(drugName + " has been removed");
        }
        else
        {
            lblMessage.setText("Please Select a Drug First");
        }
    }//GEN-LAST:event_btnDeletePatientsDrugActionPerformed

    private void lstPatientsDrugsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPatientsDrugsValueChanged
        //this sets the drugs which is selected in the drug list box
        Object selectedDrugObject = (Object)lstPatientsDrugs.getSelectedValue();
        
        selectedPatientsDrug = (PatientsDrugs)selectedDrugObject;
        
        lblMessage.setText("");
    }//GEN-LAST:event_lstPatientsDrugsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultantTreatPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultantTreatPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultantTreatPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultantTreatPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ConsultantTreatPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeletePatientsDrug;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JList<String> lstDrugs;
    private javax.swing.JList<String> lstPatientsDrugs;
    // End of variables declaration//GEN-END:variables
}
